version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: flask_backend
    ports:
      - "5000:5000"
    command: python3 app.py

  frontend:
    build:
      context: ./frontend
    container_name: node_frontend
    ports:
      - "3000:3000"
    command: node app.js
    depends_on:
      - backend